disabled_rules:
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - vertical_parameter_alignment
  - closure_parameter_position
  - todo
  - trailing_comma
  - opening_brace
  - nimble_operator
  - orphaned_doc_comment
  - type_body_length
  - file_length
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - file_header
  - attributes

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - private_outlet
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - flatmap_over_map_reduce
  - reduce_into
  - fatal_error_message
  - unneeded_parentheses_in_closure_argument
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
  - joined_default_parameter
  - override_in_extension
  - private_action
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_first_last
  - file_name_no_space
  - period_spacing
  - number_separator
  - test_case_accessibility
  - yoda_condition
  - shorthand_optional_binding
  - closure_body_length
  - collection_alignment
  - direct_return
  - discouraged_object_literal
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_xctest_method

custom_rules:
  cyrillic_letters:
    regex: "[А-Яа-яЁё]+"
    message: "Cyrillic letters in identifiers is not allowed"
    match_kinds:
      - identifier

line_length: 140

trailing_whitespace:
  ignores_empty_lines: true

function_body_length:
  warning: 100
  error: 1000

closure_body_length:
  warning: 100
  error: 1000

identifier_name:
  min_length:
    error: 1
  max_length:
    error: 50
  excluded:
    - id
    - pi
    - to
    - x
    - y
    - rc
    - dx
    - ip
    - ".*Tests.swift"

type_name:
  excluded:
    - ID

nesting:
  type_level: 3
